# Generated by Django 6.0.5 on 2026-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_deleted_at_alter_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
