# Generated by Django 6.1.1 on 2026-10-09 16:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('goal_title', models.CharField(max_length=120, verbose_name='nome da meta')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor atual')),
            ],
            options={
                'verbose_name': 'meta financeira',
                'verbose_name_plural': 'metas financeiras',
                'ordering': ['goal_title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('name', models.CharField(max_length=150, verbose_name='nome completo')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlannedBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('budget_title', models.CharField(max_length=100, verbose_name='título do orçamento')),
                ('granted_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor cedido')),
                ('allocated_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='porcentagem destinada (%)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_budgets', to='dashboard.person', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'orçamento planejado',
                'verbose_name_plural': 'orçamentos planejados',
                'ordering': ['budget_title'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('transaction_title', models.CharField(max_length=150, verbose_name='descrição')),
                ('transaction_date', models.DateField(verbose_name='data do lançamento')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], max_length=7, verbose_name='tipo')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='dashboard.person', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['person', 'transaction_date'], name='dashboard_f_person__98b123_idx'), models.Index(fields=['person', 'transaction_type', 'transaction_date'], name='dashboard_f_person__a89af8_idx')],
            },
        ),
    ]
